summary: Update centos-9 64 bits image with the latest updates and test dependencies

systems: [centos-9-64-base]

execute: |
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Normalize fedora base url among fedora versions
        mv /etc/yum.repos.d/centos.repo /etc/yum.repos.d/centos.repo.old
        cp "$PWD"/centos.repo /etc/yum.repos.d/centos.repo

        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db
        distro_upgrade_packages

        remove_pkg_blacklist

        REBOOT
    fi

    # Configure ntp to ntp.ubuntu.com
    sed -i -e 's/^pool.*/pool ntp.ubuntu.com iburst/g' /etc/chrony.conf
    sed -i -e 's/^#pool.*/pool ntp.ubuntu.com iburst/g' /etc/chrony.conf
    systemctl restart chronyd
    sleep 5
    timedatectl set-ntp yes
    timedatectl | MATCH "System clock synchronized: yes"
    timedatectl | MATCH "NTP service: active"

    # Clean the disk
    clean_machine

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"

