summary: Update centos-9 64 bits image with the latest updates and test dependencies

systems: [centos-9-64-base]

execute: |
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Normalize fedora base url among fedora versions
        mv /etc/yum.repos.d/centos.repo /etc/yum.repos.d/centos.repo.old
        cp "$PWD"/centos.repo /etc/yum.repos.d/centos.repo

        # Configure the epel and epel-next repos
        dnf config-manager --set-enabled crb
        dnf install -y epel-release epel-next-release || true
        
        mv /etc/yum.repos.d/epel.repo /etc/yum.repos.d/epel.repo.old        
        cp "$PWD"/epel.repo /etc/yum.repos.d/epel.repo

        mv /etc/yum.repos.d/epel-next.repo /etc/yum.repos.d/epel-next.repo.old
        cp "$PWD"/epel-next.repo /etc/yum.repos.d/epel-next.repo

        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db
        distro_install_package wget
        distro_upgrade_packages

        remove_pkg_blacklist

        REBOOT
    fi

    # Configure ntp to ntp.ubuntu.com
    sed -i -e 's/^pool.*/pool ntp.ubuntu.com iburst/g' /etc/chrony.conf
    sed -i -e 's/^#pool.*/pool ntp.ubuntu.com iburst/g' /etc/chrony.conf
    systemctl restart chronyd
    sleep 5
    timedatectl set-ntp yes

    sed -i 's/SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
    setenforce Permissive

    # Clean the disk
    clean_machine

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"

