summary: Update Ubuntu xenial/bionic/focal/jammy 64 bits image with the latest updates and kvm enabled

systems: [ubuntu-16.04-64-virt-enabled, ubuntu-18.04-64-virt-enabled, ubuntu-20.04-64-base, ubuntu-20.04-arm-64, ubuntu-22.04-64-base, ubuntu-22.04-arm-64, ubuntu-22.10-64-base, ubuntu-24.04-64-base, ubuntu-24.04-arm-64]

environment:
    LICENSES: https://www.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx

execute: |
    case "$SPREAD_SYSTEM" in
        ubuntu-16.04-64*)
            TARGET_SYSTEM=ubuntu-16.04-64-virt-enabled
        ;;
        ubuntu-18.04-64*)
            TARGET_SYSTEM=ubuntu-18.04-64-virt-enabled
        ;;
        ubuntu-20.04-64*)
            TARGET_SYSTEM=ubuntu-20.04-64-virt-enabled
        ;;
        ubuntu-20.04-arm-64*)
            TARGET_SYSTEM=ubuntu-20.04-arm-64-virt-enabled
        ;;
        ubuntu-22.04-64*)
            TARGET_SYSTEM=ubuntu-22.04-64-virt-enabled
        ;;
        ubuntu-22.04-arm-64*)
            TARGET_SYSTEM=ubuntu-22.04-arm-64-virt-enabled
        ;;
        ubuntu-22.10-64*)
            TARGET_SYSTEM=ubuntu-22.10-64-virt-enabled
        ;;
        ubuntu-24.04-64*)
            TARGET_SYSTEM=ubuntu-24.04-64-virt-enabled
        ;;
        ubuntu-24.04-arm-64*)
            TARGET_SYSTEM=ubuntu-24.04-arm-64-virt-enabled
        ;;
        *)
            echo "System not supported"
            exit 1
        ;;
    esac

    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db

        # Install virtualization dependencies and configure them
        if [[ "$SPREAD_SYSTEM" = ubuntu-24.04* ]]; then
            distro_install_package snapd qemu-utils genisoimage sshpass qemu-kvm cloud-image-utils ovmf kpartx
        else    
            distro_install_package snapd qemu qemu-utils genisoimage sshpass qemu-kvm cloud-image-utils ovmf kpartx
        fi

        distro_upgrade_packages
        remove_pkg_blacklist
        REBOOT
    fi

    # Avoid checking for new release, it could cause lock on apt
    sed -i 's/^Prompt=.*$/Prompt=never/' /etc/update-manager/release-upgrades

    # Disable daily checks for updates to avoid apt locks
    sudo systemctl disable --now apt-daily{,-upgrade}.{timer,service}

    # Remove lxd snap
    if snap list lxd; then
        snap remove lxd
    fi

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk_with_licences "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK" "$LICENSES"

restore: |
    case "$SPREAD_SYSTEM" in
        ubuntu-16.04-64*)
            TARGET_SYSTEM=ubuntu-16.04-64-virt-enabled
        ;;
        ubuntu-18.04-64*)
            TARGET_SYSTEM=ubuntu-18.04-64-virt-enabled
        ;;
        ubuntu-20.04-64*)
            TARGET_SYSTEM=ubuntu-20.04-64-virt-enabled
        ;;
        ubuntu-20.04-arm-64*)
            TARGET_SYSTEM=ubuntu-20.04-arm-64-virt-enabled
        ;;
        ubuntu-22.04-64*)
            TARGET_SYSTEM=ubuntu-22.04-64-virt-enabled
        ;;
        ubuntu-22.04-arm-64*)
            TARGET_SYSTEM=ubuntu-22.04-arm-64-virt-enabled
        ;;
        ubuntu-22.10-64*)
            TARGET_SYSTEM=ubuntu-22.10-64-virt-enabled
        ;;
        ubuntu-24.04-64*)
            TARGET_SYSTEM=ubuntu-24.04-64-virt-enabled
        ;;
        ubuntu-24.04-arm-64*)
            TARGET_SYSTEM=ubuntu-24.04-arm-64-virt-enabled
        ;;
        *)
            echo "System not supported"
            exit 1
        ;;
    esac

    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
