summary: Update Ubuntu xenial/bionic/focal 64 bits image with the latest updates and kvm enabled

systems: [ubuntu-16.04-64-base, ubuntu-18.04-64-base, ubuntu-20.04-64-base, ubuntu-20.10-64-base]

environment:
    LICENSES: https://www.googleapis.com/compute/v1/projects/vm-options/global/licenses/enable-vmx

execute: |
    case "$SPREAD_SYSTEM" in
        ubuntu-16.04-64*)
            TARGET_SYSTEM=ubuntu-16.04-64-virt-enabled
        ;;
        ubuntu-18.04-64-uefi*)
            TARGET_SYSTEM=ubuntu-18.04-64-virt-uefi-enabled
        ;;
        ubuntu-18.04-64*)
            TARGET_SYSTEM=ubuntu-18.04-64-virt-enabled
        ;;
        ubuntu-19.10-64*)
            TARGET_SYSTEM=ubuntu-19.10-64-virt-enabled
        ;;
        ubuntu-20.04-64-uefi*)
            TARGET_SYSTEM=ubuntu-20.04-64-virt-uefi-enabled
        ;;
        ubuntu-20.04-64*)
            TARGET_SYSTEM=ubuntu-20.04-64-virt-enabled
        ;;
        ubuntu-20.10-64*)
            TARGET_SYSTEM=ubuntu-20.10-64-virt-enabled
        ;;
        *)
            echo "System not supported"
            exit 1
        ;;
    esac

    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db

        # Install virtualization dependencies and configure them
        distro_install_package snapd qemu qemu-utils genisoimage sshpass qemu-kvm cloud-image-utils ovmf kpartx
 
        if [[ "$SPREAD_SYSTEM" =~ ubuntu-20.04* ]]; then
            apt remove -y linux-headers-5.4.0-1024-gcp
            apt remove -y linux-image-5.4.0-1024-gcp
            wget http://security.ubuntu.com/ubuntu/pool/main/l/linux-gcp/linux-modules-4.15.0-1078-gcp_4.15.0-1078.88~16.04.1_amd64.deb
            wget http://security.ubuntu.com/ubuntu/pool/main/l/linux-gcp/linux-gcp-headers-4.15.0-1078_4.15.0-1078.88~16.04.1_amd64.deb
            wget http://security.ubuntu.com/ubuntu/pool/universe/l/linux-signed-gcp-4.15/linux-image-4.15.0-1078-gcp_4.15.0-1078.88_amd64.deb
            wget http://security.ubuntu.com/ubuntu/pool/main/l/linux-gcp/linux-modules-4.15.0-1078-gcp_4.15.0-1078.88~16.04.1_amd64.deb
            dpkg -i *.deb
        fi

        distro_upgrade_packages
        remove_pkg_blacklist
        REBOOT
    fi

    # Avoid checking for new release, it could cause lock on apt
    sed -i 's/^Prompt=.*$/Prompt=never/' /etc/update-manager/release-upgrades

    # Disable daily checks for updates to avoid apt locks
    sudo systemctl disable --now apt-daily{,-upgrade}.{timer,service}

    # Remove lxd snap
    if snap list lxd; then
        snap remove lxd
    fi

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk_with_licences "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK" "$LICENSES"

restore: |
    case "$SPREAD_SYSTEM" in
        ubuntu-16.04-64*)
            TARGET_SYSTEM=ubuntu-16.04-64-virt-enabled
        ;;
        ubuntu-18.04-64-uefi*)
            TARGET_SYSTEM=ubuntu-18.04-64-virt-uefi-enabled
        ;;
        ubuntu-18.04-64*)
            TARGET_SYSTEM=ubuntu-18.04-64-virt-enabled
        ;;
        ubuntu-19.10-64*)
            TARGET_SYSTEM=ubuntu-19.10-64-virt-enabled
        ;;
        ubuntu-20.04-64-uefi*)
            TARGET_SYSTEM=ubuntu-20.04-64-virt-uefi-enabled
        ;;
        ubuntu-20.04-64*)
            TARGET_SYSTEM=ubuntu-20.04-64-virt-enabled
        ;;
        ubuntu-20.10-64*)
            TARGET_SYSTEM=ubuntu-20.10-64-virt-enabled
        ;;
        *)
            echo "System not supported"
            exit 1
        ;;
    esac

    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
