summary: Update amazon linux 2 image in openstack account and install test dependencies

systems: [amazon-linux-2-64-base]

environment:
    TARGET_SYSTEM: amazon-linux-2-64

execute: |
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade
        distro_update_package_db
        distro_upgrade_packages
        #install_test_dependencies "$TARGET_SYSTEM"
        remove_pkg_blacklist
        REBOOT
    fi

    # Clean the disk
    clean_machine

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"
    sync
