summary: Add new amazon linux 2 image

systems: [ubuntu-*]

environment:
    IMAGE_URL: '$(HOST: echo "${SPREAD_IMAGE_URL:-https://cdn.amazonlinux.com/os-images/2017.12.0.20180222/kvm/amzn2-kvm-2017.12.0.20180222-x86_64.xfs.gpt.qcow2}")'
    IMAGE_NAME: '$(HOST: echo "${SPREAD_IMAGE_NAME:-amazon-linux-64-base.qcow2}")'

execute: |
    source_image_name="$(basename $IMAGE_URL)"
    wget -q -O "$IMAGE_NAME" "$IMAGE_URL"

    # Install test dependencies
    apt install -y qemu-utils

    # Get the raw image    
    qemu-img convert -O raw "$IMAGE_NAME" disk.raw

    # Get /dev/sda1 parition offset
    OFFSET=$( sfdisk -J disk.raw | jq '.partitiontable.partitions[0].start * 512' )

    if [ -z $OFFSET ]; then
        echo "failed to calculate offset"
        exit 1
    fi

    # Either become root and paste these line-by-line or the whole block at once
    OFFSET="$OFFSET" sh -c '\
    # Make mounting directory
    mkdir -p /mnt/disk3
    # Mount the image and prepare the chroot
    mount -o loop,offset=$OFFSET disk3.raw /mnt/disk3
    mount -t proc /proc /mnt/disk3/proc
    mount --rbind /sys /mnt/disk3/sys
    mount --make-rslave /mnt/disk3/sys
    mount --rbind /dev /mnt/disk3/dev
    mount --make-rslave /mnt/disk3/dev'

    # Copy nameservers
    cp /etc/resolv.conf /mnt/disk/etc/

    # Make sure cloud init is installed
    chroot /mnt/disk /bin/bash -c "yum --nogpgcheck makecache"
    chroot /mnt/disk /bin/bash -c "yum install -y cloud-init"

    # Clean other init script witch make the user data to fail
    rm -f /mnt/disk/etc/cloud/cloud.cfg.d/*
    cp cloud.cfg /mnt/disk/etc/cloud/cloud.cfg
    cp 05_logging.cfg /mnt/disk/etc/cloud/cloud.cfg.d/05_logging.cfg

    # The default dns server is not working properly in google
    # so we force using also 8.8.8.8
    echo "nameserver 8.8.8.8" | tee -a /mnt/disk/etc/resolv.conf

    # Configure time
    chroot /mnt/disk /bin/bash -c "ln -sf /usr/share/zoneinfo/UTC /etc/localtime"

    # Create the disk image
    sleep 30
    umount -AR /mnt/disk
    sleep 30    
    qemu-img convert -O qcow2 disk.raw "$IMAGE_NAME"

    gsutil cp "$IMAGE_NAME" gs://snapd-spread-tests/images/openstack/"$IMAGE_NAME"  

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"