backends:
  linode:
    systems:
    - ubuntu-17.10-64:
        password: 62f6aa345e794a24
        address: 66.175.211.103
        data:
          id: 2865596
          label: Spread-30
          config: 4142568
          root: 7951241
          swap: 7951242
