summary: Add new opensuse 15.6 image

systems: [ubuntu-*]

environment:
    IMAGE_URL: '$(HOST: echo "${SPREAD_IMAGE_URL:-https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.6/images/openSUSE-Leap-15.6.x86_64-NoCloud.qcow2}")'
    IMAGE_NAME: '$(HOST: echo "${SPREAD_IMAGE_NAME:-opensuse-15.6-64-base.qcow2}")'

execute: |
    source_image_name="$(basename $IMAGE_URL)"
    wget -q -O "$IMAGE_NAME" "$IMAGE_URL"
    gsutil cp "$IMAGE_NAME" gs://snapd-spread-tests/images/openstack/"$IMAGE_NAME"

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"