summary: Update arch linux image in google account

systems: [arch-linux-64-base]

environment:
    TARGET_SYSTEM: arch-linux-64

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade
        distro_update_package_db
        distro_upgrade_packages
        install_test_dependencies "$TARGET_SYSTEM"
        distro_install_package inetutils
        remove_pkg_blacklist

        # since 4.16, kernel crng init can take significant time, thus services
        # depending on crypto such as sshd will take longer to start
        distro_install_package haveged
        systemctl enable --now haveged

        # Force systmed 252 to avoid error in the integration with dbus
        pacman -U --noconfirm /var/cache/pacman/pkg/systemd-252.3-1-x86_64.pkg.tar.zst
        mkinitcpio -p linux
        sed -i -e 's/#IgnorePkg   =/IgnorePkg = systemd/g' /etc/pacman.conf

        REBOOT
    fi

    # Install grub to make it compatible with boot-state tool
    distro_install_package grub
    mkdir -p /boot/grub/
    if [ ! -e /boot/grub/grubenv ]; then
        echo "# GRUB Environment Block" > /boot/grub/grubenv
        echo "#######################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################################" >> /boot/grub/grubenv
    fi

    # Enable apparmor on systemd-boot
    if ! MATCH "apparmor=1" < /boot/loader/entries/arch.conf; then
        distro_install_package apparmor
        systemctl enable apparmor

        sed -e 's/options /options apparmor=1 security=apparmor /g' -i /boot/loader/entries/arch.conf
    fi

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk_with_os_features "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK" "UEFI_COMPATIBLE"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
