summary: Add new arch linux image to google account

systems: [arch-linux-64-external]

environment:
    TARGET_SYSTEM: arch-linux-64-external

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    # Add a base image by doing:
    # gcloud compute instances create my-new-arch-linux --image-project=arch-linux-gce --image-family=arch --zone=us-east1-b
    # Then create a snapshot from the running instace
    # And then create the image from the snapshot

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images