summary: Update fedora image with the latest updates and test dependencies with selinux permissive

systems: [fedora-40-64-base]

execute: |
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Normalize fedora base url among fedora versions
        sed -i -s -E -e 's@^#?baseurl=http://download.example/@baseurl=http://dl.fedoraproject.org/@g' /etc/yum.repos.d/fedora*.repo
        sed -i -e 's/metalink=/#metalink=/g' /etc/yum.repos.d/fedora*.repo
        dnf --refresh -y makecache

        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db
        distro_install_package kernel-modules
        distro_upgrade_packages

        #install_test_dependencies "$TARGET_SYSTEM"
        remove_pkg_blacklist

        REBOOT
    fi

    # Set selinux as permissive
    sed -i 's/SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config
    setenforce Permissive

    # Clean disk before create the shapshot
    clean_machine

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"

