summary: Add new fedora 42 image

systems: [ubuntu-*]

environment:
    IMAGE_URL: '$(HOST: echo "${SPREAD_IMAGE_URL:-https://cloud-images.ubuntu.com/questing/current/questing-server-cloudimg-amd64.img}")'
    IMAGE_NAME: '$(HOST: echo "${SPREAD_IMAGE_NAME:-questing-server-cloudimg-amd64.qcow2}")'

execute: |
    source_image_name="$(basename $IMAGE_URL)"
    wget -q -O "$IMAGE_NAME" "$IMAGE_URL"
    gsutil cp "$IMAGE_NAME" gs://snapd-spread-tests/images/openstack/"$IMAGE_NAME"

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"