summary: Update amazon linux 2023 image in google account and install test dependencies

systems: [amazon-linux-2023-64-base]

environment:
    TARGET_SYSTEM: amazon-linux-2023-64

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade
        distro_update_package_db
        distro_upgrade_packages
        #install_test_dependencies "$TARGET_SYSTEM"
        remove_pkg_blacklist
        REBOOT
    fi

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk_with_os_features "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK" "UEFI_COMPATIBLE"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
