summary: Update centos 9 image in google account and install test dependencies

systems: [centos-9-64-base]

environment:
    TARGET_SYSTEM: centos-9-64

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade
        distro_update_package_db
        distro_upgrade_packages

        wget https://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/xdelta-3.1.0-4.el8.x86_64.rpm
        rpm -i xdelta-3.1.0-4.el8.x86_64.rpm
        dnf --enablerepo=crb install -y glibc-static
        dnf --enablerepo=crb install -y python3-docutils

        # The test dependencies need to be updated 
        install_test_dependencies "$TARGET_SYSTEM"

        remove_pkg_blacklist
        REBOOT
    fi

    # Set selinux as permissive
    sed -i 's/SELINUX=.*/SELINUX=permissive/g' /etc/selinux/config

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
