summary: Add new fedora 35 64 bits image to google account

environment:
    TARGET_SYSTEM: fedora-35-64-base
    IMAGE_FILE: fedora-35-64
    IMAGE_URL: https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/x86_64/images/Fedora-Cloud-Base-GCP-35-1.2.x86_64.tar.gz
               
execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    # Get the image
    wget -O "${IMAGE_FILE}.tar.gz" "$IMAGE_URL"

    # Copy fedora linux image to spread-images bucket
    gsutil cp "${IMAGE_FILE}.tar.gz" "gs://${BUCKET_NAME}/"
    
    # Create the image in snapd-spread project
    delete_image "$IMAGE" "$FAMILY"
    create_image_from_bucket "$IMAGE" "$FAMILY" "$DESCRIPTION" "${IMAGE_FILE}.tar.gz"

restore: |
    sudo umount -AR /mnt/disk || true
    rm -f "${IMAGE_FILE}.tar.gz"
