summary: Add new tumbleweed 64 bits image to google account created from openstack image

systems: [opensuse-15.6-64-base]

environment:
    TARGET_SYSTEM: opensuse-tumbleweed-64-base

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        mkdir /etc/zypp/repos.d/old
        mv /etc/zypp/repos.d/*.repo /etc/zypp/repos.d/old

        zypper ar -f -c http://download.opensuse.org/tumbleweed/repo/oss repo-oss
        zypper ar -f -c http://download.opensuse.org/tumbleweed/repo/non-oss repo-non-oss
        zypper ar -f -c http://download.opensuse.org/tumbleweed/repo/debug repo-debug
        zypper ar -f -c http://download.opensuse.org/update/tumbleweed/ repo-update
        
        zypper cc -a && zypper ref && zypper --non-interactive dup --allow-vendor-change
        zypper refresh --force
        zypper dist-upgrade

        REBOOT
    fi
    
    # Make sure we have the /etc/environment file with the PATH
    touch /etc/environment

    # Clean disk before create the snapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk_with_os_features "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK" "UEFI_COMPATIBLE"
    
restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images

