summary: Remove old images for a specific images family

environment:
    TARGET_SYSTEM: "$(HOST: echo ${SPREAD_TARGET_SYSTEM:-SPREAD_SYSTEM})"
    SYSTEM_BACKUPS: "$(HOST: echo ${SPREAD_SYSTEM_BACKUPS:-0})"

execute: |
    test "$SYSTEM_BACKUPS" -ge 0

    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/google.sh"

    # We get the images for that family ordered by creation timestamp descendent, and then
    # get the images from the list leaving the initial $SYSTEM_BACKUPS + 1
    # We leave the +1 to keep the last image which is not the backup
    # In case the SYSTEM_BACKUPS is 0, then all the images but the last one will be removed
    images="$(get_ordered_image_names $FAMILY | tail -n +$(( $SYSTEM_BACKUPS + 2 )) )"

    for image in $images; do
        delete_image "$image" "$FAMILY"
    done
