summary: Release an specific temporal image

environment:
    # Image id used to release
    TMP_IMAGE_NAME: '$(HOST: echo "${SPREAD_TMP_IMAGE_NAME:-}")'
    TMP_IMAGE_FAMILY: '$(HOST: echo "${SPREAD_TMP_IMAGE_FAMILY:-}")'
    TARGET_SYSTEM: '$(HOST: echo "${SPREAD_TARGET_SYSTEM_:-}")'

execute: |
    TMP_IMAGE_ID= . "$TESTSLIB/names.sh"
    . "$TESTSLIB/google.sh"

    echo "snapd test suite passed, clonning tmp image"
    final_image="$IMAGE"
    final_family="$FAMILY"
    final_description="$DESCRIPTION"
    create_image_from_image "$final_image" "$final_family" "$final_description" "$TMP_IMAGE_NAME"

    echo "deleting tmp image"
    delete_image "$TMP_IMAGE_NAME" "$TMP_IMAGE_FAMILY"
