summary: Update opensuse tumbleweed base image with the latest updates

systems: [opensuse-tumbleweed-64-base]

environment:
    TARGET_SYSTEM: opensuse-tumbleweed-64-base

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db        
        distro_upgrade_packages

        remove_pkg_blacklist
        REBOOT
    fi

    # Make sure we have google-compute-engine installed
    distro_purge_package google-guest-configs
    distro_install_package google-compute-engine-init


    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk_with_os_features "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK" "UEFI_COMPATIBLE"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
