summary: Update debian-12 64 bits image with the latest updates and test dependencies

systems: [debian-12-64-base]

environment:
    TARGET_SYSTEM: debian-12-64

execute: |
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db
        distro_upgrade_packages

        install_pkg_dependencies
        install_test_dependencies "$TARGET_SYSTEM"

        remove_pkg_blacklist

        REBOOT
    fi

    # Disable daily checks for updates to avoid apt locks
    sudo systemctl disable --now apt-daily{,-upgrade}.{timer,service}

    # Setup ntp server depending on the openstack environment
    update_ntp

    # Clean the disk
    clean_machine

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"

