summary: Update arch linux base image in google compute engine

systems: [arch-linux-64-base]

environment:
    TARGET_SYSTEM: arch-linux-64-base

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade
        distro_update_package_db
        distro_upgrade_packages

        # Install reflector and enable it to improve the mirrors performance
        distro_install_package reflector
        sed '/--country /d' -i /etc/xdg/reflector/reflector.conf
        echo '--country "United States"' >> /etc/xdg/reflector/reflector.conf
        systemctl enable reflector
        systemctl start reflector

        distro_install_package inetutils vim

        REBOOT
    fi

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
