summary: Update opensuse 15.6 64 bits image with the latest updates and test dependencies

systems: [opensuse-15.6-64-base]

environment:
    TARGET_SYSTEM: opensuse-15.6-64-base

execute: |
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Cleanup non required repos
        rm -f /etc/zypp/repos.d/repo-sle-*.repo
        rm -f /etc/zypp/repos.d/*-debug*.repo
        rm -f /etc/zypp/repos.d/*-backports*.repo

        # Use mirrorcache avoids errors trying to access the repo metadata
        # It is possible to use https://ftp.icm.edu.pl/pub/Linux/opensuse/ as backup
        sed -i -s -E -e 's@^baseurl=http://download.opensuse.org/@baseurl=http://mirrors.dotsrc.org/opensuse/@g' /etc/zypp/repos.d/repo*.repo

        # Make the upgrade and install the dependencies needed to run snapd tests
        # In case some repo cannot be updated due to proxy restriction
        distro_update_package_db || true
        distro_upgrade_packages

        REBOOT
    fi

    # Configure ntp to ntp.ubuntu.com
    sed -i -e 's/^pool.*/pool ntp.ubuntu.com iburst/g' /etc/chrony.conf
    sed -i -e 's/^#pool.*/pool ntp.ubuntu.com iburst/g' /etc/chrony.conf
    systemctl restart chronyd
    sleep 5
    timedatectl set-ntp yes
    sleep 5

    # Clean the disk
    clean_machine

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"

