summary: Add new fedora 37 64 bits image to google account

environment:
    TARGET_SYSTEM: fedora-37-64-base
    IMAGE_FILE: fedora-37-64
    IMAGE_URL: https://edgeuno-bog2.mm.fcix.net/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-GCP-37-1.7.x86_64.tar.gz
               
execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    # Get the image
    wget -O "${IMAGE_FILE}.tar.gz" "$IMAGE_URL"

    # Copy fedora linux image to spread-images bucket
    gsutil cp "${IMAGE_FILE}.tar.gz" "gs://${BUCKET_NAME}/"
    
    # Create the image in snapd-spread project
    delete_image "$IMAGE" "$FAMILY"
    create_image_from_bucket "$IMAGE" "$FAMILY" "$DESCRIPTION" "${IMAGE_FILE}.tar.gz"

restore: |
    sudo umount -AR /mnt/disk || true
    rm -f "${IMAGE_FILE}.tar.gz"
