summary: Add new ubuntu bionic 32 bits image to google account

backends: [google-nested]

environment:
    TARGET_SYSTEM: ubuntu-22.04-64-devstack

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/utils.sh"

    apt update
    apt upgrade -y

    useradd -s /bin/bash -d /opt/stack -m stack
    chmod +x /opt/stack
    echo "stack ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/stack

    git clone https://opendev.org/openstack/devstack
    cp local.conf devstack
    chown -R stack:stack devstack
    
    mv devstack /opt/stack
    sudo -u stack -i /opt/stack/devstack/stack.sh

    # Clean disk before create the shapshot
    clean_machine

    # Create a new image based on the current disk
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
