summary: Add new opensuse leap 15.1 64 bits image to google account

systems: [opensuse-15.1-64-external]

environment:
    TARGET_SYSTEM: opensuse-15.1-64-base

execute: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    # Clean disk before create the shapshot
    clean_machine

    # Create the image in computeengine project
    delete_image "$IMAGE" "$FAMILY"
    create_image_from_disk "$IMAGE" "$FAMILY" "$DESCRIPTION" "$DISK"

restore: |
    . "$TESTSLIB/google.sh"
    . "$TESTSLIB/names.sh"

    delete_snapshot "$DISK"
    delete_deprecated_images
