summary: Update opensuse 15.5 64 bits image with the latest updates and test dependencies

systems: [opensuse-15.5-64-base]

execute: |
    . "$TESTSLIB/pkgdb.sh"
    . "$TESTSLIB/utils.sh"

    if [ "$SPREAD_REBOOT" = 0 ]; then
        # Make the upgrade and install the dependencies needed to run snapd tests
        distro_update_package_db
        distro_upgrade_packages

        remove_pkg_blacklist

        REBOOT
    fi

    # Configure ntp to ntp.ubuntu.com
    sed -i -e 's/^pool.*/pool ntp.ubuntu.com iburst/g' /etc/chrony.conf
    sed -i -e 's/^#pool.*/pool ntp.ubuntu.com iburst/g' /etc/chrony.conf
    systemctl restart chronyd
    sleep 5
    timedatectl set-ntp yes
    sleep 5

    # Clean the disk
    clean_machine

restore: |
    # Remove the project path content
    rm -rf "$PROJECT_PATH"

