name: Clean OS images

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 0'

jobs:
  clean-images-ps6:
    runs-on: [self-hosted, spread-enabled]
    environment: OS_AMD64_PS6
    steps:
    - name: Ensure the workspace is clean
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

    - name: Checkout code 
      uses: actions/checkout@v4
      with:
          ref: master

    - name: Delete old images
      env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_IDENTITY_API_VERSION: ${{ vars.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ vars.OS_INTERFACE }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_DOMAIN_NAME: ${{ vars.OS_PROJECT_DOMAIN_NAME }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ vars.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
      shell: bash
      run: |
          ./lib/openstack.sh clean-images
  
    - name: Cleanup job workspace after run tests
      if: always()
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

  clean-volumes-ps6:
    runs-on: [self-hosted, spread-enabled]
    steps:
    - name: Ensure the workspace is clean
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: master

    - name: Delete orphan volumes
      env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_IDENTITY_API_VERSION: ${{ vars.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ vars.OS_INTERFACE }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_DOMAIN_NAME: ${{ vars.OS_PROJECT_DOMAIN_NAME }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ vars.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
      run: |
          ./lib/openstack.sh clean-volumes
  
    - name: Cleanup job workspace after run tests
      if: always()
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

  clean-images-ps7:
    runs-on: [self-hosted, spread-enabled]
    environment: OS_AMD64_PS7
    steps:
    - name: Ensure the workspace is clean
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

    - name: Checkout code 
      uses: actions/checkout@v4
      with:
          ref: master

    - name: Delete old images
      env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_IDENTITY_API_VERSION: ${{ vars.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ vars.OS_INTERFACE }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_DOMAIN_NAME: ${{ vars.OS_PROJECT_DOMAIN_NAME }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ vars.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
      shell: bash
      run: |
          ./lib/openstack.sh clean-images
  
    - name: Cleanup job workspace after run tests
      if: always()
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

  clean-images-arm-ps7:
    runs-on: [self-hosted, spread-enabled]
    environment: OS_ARM64_PS7
    steps:
    - name: Ensure the workspace is clean
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

    - name: Checkout code 
      uses: actions/checkout@v4
      with:
          ref: master

    - name: Delete old images
      env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_IDENTITY_API_VERSION: ${{ vars.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ vars.OS_INTERFACE }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_DOMAIN_NAME: ${{ vars.OS_PROJECT_DOMAIN_NAME }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ vars.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
      shell: bash
      run: |
          ./lib/openstack.sh clean-images
  
    - name: Cleanup job workspace after run tests
      if: always()
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"