name: Weekly Openstack images update

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * 0'

jobs:
  update-image-ps6:
    name: os-amd64-ps6 (${{ matrix.group }})
    runs-on: [self-hosted, spread-enabled]
    environment: OS_AMD64_PS6
    strategy:
      fail-fast: false
      matrix:
        include:
          - group: debian sid
            task: debian-sid-64
            source: debian-sid-64-base
            target: debian-sid-64
            property:

          - group: centos 9
            task: centos-9-64
            source: centos-9-64-base
            target: centos-9-64
            property:

          - group: fedora 40
            task: fedora-40-64
            source: fedora-40-64-base
            target: fedora-40-64
            property:
          - group: fedora 41
            task: fedora-41-64
            source: fedora-41-64-base
            target: fedora-41-64
            property:

          - group: opensuse 15.6
            task: opensuse-15.6-64
            source: opensuse-15.6-64-base
            target: opensuse-15.6-64
            property:
          - group: opensuse tumbleweed
            task: opensuse-tumbleweed-64
            source: opensuse-tumbleweed-64-base
            target: opensuse-tumbleweed-64
            property:
          - group: opensuse tumbleweed selinux enabled
            task: opensuse-tumbleweed-64-selinux
            source: opensuse-tumbleweed-64-base
            target: opensuse-tumbleweed-64-selinux-enabled
            property:

    steps:
    - name: Ensure the workspace is clean
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: master

    - name: Run test
      env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_IDENTITY_API_VERSION: ${{ vars.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ vars.OS_INTERFACE }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_DOMAIN_NAME: ${{ vars.OS_PROJECT_DOMAIN_NAME }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ vars.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
      shell: bash
      run: |
          property_param=""
          if [ -n "${{ matrix.property }}" ]; then
            property_param="--property ${{ matrix.property }}"
          fi

          ./lib/openstack.sh update-image --no-checks --backend openstack --task "${{ matrix.task }}" --source-system "${{ matrix.source }}" --target-system "${{ matrix.target }}" --target-image snapd-spread/"${{ matrix.target }}" $property_param
  
    - name: Discard spread workers
      if: always()
      run: |
        shopt -s nullglob;
        for r in .spread-reuse.*.yaml; do
          spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')";
        done

  update-image-ps7:
    name: os-amd64-ps7 (${{ matrix.group }})
    runs-on: [self-hosted, spread-enabled]
    environment: OS_AMD64_PS7
    strategy:
      fail-fast: false
      matrix:
        include:
          - group: ubuntu 16.04
            task: ubuntu-16.04-64
            source: ubuntu-16.04-64-base
            target: ubuntu-16.04-64
            property:
          - group: ubuntu 18.04
            task: ubuntu-18.04-64
            source: ubuntu-18.04-64-base
            target: ubuntu-18.04-64
            property:
          - group: ubuntu 20.04
            task: ubuntu-20.04-64
            source: ubuntu-20.04-64-base
            target: ubuntu-20.04-64
            property:
          - group: ubuntu 22.04
            task: ubuntu-22.04-64
            source: ubuntu-22.04-64-base
            target: ubuntu-22.04-64
            property:
          - group: ubuntu 24.04
            task: ubuntu-24.04-64
            source: ubuntu-24.04-64-base
            target: ubuntu-24.04-64
            property:
          - group: ubuntu 25.04
            task: ubuntu-25.04-64
            source: ubuntu-25.04-64-base
            target: ubuntu-25.04-64
            property:
          - group: ubuntu 25.10
            task: ubuntu-25.10-64
            source: ubuntu-25.10-64-base
            target: ubuntu-25.10-64
            property:

          - group: ubuntu 20.04 uefi
            task: ubuntu-20.04-64
            source: ubuntu-20.04-64-base
            target: ubuntu-20.04-64-uefi
            property: hw_firmware_type=uefi
          - group: ubuntu 22.04 uefi
            task: ubuntu-22.04-64
            source: ubuntu-22.04-64-base
            target: ubuntu-22.04-64-uefi
            property: hw_firmware_type=uefi
          - group: ubuntu 24.04 uefi
            task: ubuntu-24.04-64
            source: ubuntu-24.04-64-base
            target: ubuntu-24.04-64-uefi
            property: hw_firmware_type=uefi

          - group: debian 12
            task: debian-12-64
            source: debian-12-64-base
            target: debian-12-64
            property:

          - group: amazon-linux 2
            task: amazon-linux-2-64
            source: amazon-linux-2-base
            target: amazon-linux-2
            property: os_secure_boot=required
          - group: amazon-linux 2023
            task: amazon-linux-2023-64
            source: amazon-linux-2023-base
            target: amazon-linux-2023
            property: os_secure_boot=required

          - group: arch-linux
            task: arch-linux-64
            source: arch-linux-base
            target: arch-linux
            property:

    steps:
    - name: Ensure the workspace is clean
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: master

    - name: Run test
      env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_IDENTITY_API_VERSION: ${{ vars.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ vars.OS_INTERFACE }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_DOMAIN_NAME: ${{ vars.OS_PROJECT_DOMAIN_NAME }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ vars.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
      shell: bash
      run: |
          property_param=""
          if [ -n "${{ matrix.property }}" ]; then
            property_param="--property ${{ matrix.property }}"
          fi
          ./lib/openstack.sh update-image --no-checks --backend openstack-ps7 --task "${{ matrix.task }}" --source-system "${{ matrix.source }}" --target-system "${{ matrix.target }}" --target-image snapd-spread/"${{ matrix.target }}" $property_param
  
    - name: Discard spread workers
      if: always()
      run: |
        shopt -s nullglob;
        for r in .spread-reuse.*.yaml; do
          spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')";
        done

  update-image-arm-ps7:
    name: os-arm64-ps7 (${{ matrix.group }})
    runs-on: [self-hosted, spread-enabled]
    environment: OS_ARM64_PS7
    strategy:
      fail-fast: false
      matrix:
        include:
          - group: ubuntu 22.04
            task: ubuntu-22.04-arm-64
            source: ubuntu-22.04-arm-64-base
            target: ubuntu-22.04-arm-64
            property:
          - group: ubuntu 24.04
            task: ubuntu-24.04-arm-64
            source: ubuntu-24.04-arm-64-base
            target: ubuntu-24.04-arm-64
            property:
          - group: ubuntu 24.04 uefi
            task: ubuntu-24.04-arm-64
            source: ubuntu-24.04-arm-64-base
            target: ubuntu-24.04-arm-64-uefi
            property: hw_firmware_type=uefi


    steps:
    - name: Ensure the workspace is clean
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: master

    - name: Run test
      env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_IDENTITY_API_VERSION: ${{ vars.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ vars.OS_INTERFACE }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_DOMAIN_NAME: ${{ vars.OS_PROJECT_DOMAIN_NAME }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
          OS_USER_DOMAIN_NAME: ${{ vars.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
      shell: bash
      run: |
          property_param=""
          if [ -n "${{ matrix.property }}" ]; then
            property_param="--property ${{ matrix.property }}"
          fi

          ./lib/openstack.sh update-image --no-checks --backend openstack-arm-ps7 --task "${{ matrix.task }}" --source-system "${{ matrix.source }}" --target-system "${{ matrix.target }}" --target-image snapd-spread/"${{ matrix.target }}" $property_param
  
    - name: Discard spread workers
      if: always()
      run: |
        shopt -s nullglob;
        for r in .spread-reuse.*.yaml; do
          spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')";
        done