name: Update Google images

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * 0'

jobs:
  update-image:
    name: ${{ matrix.group }}
    runs-on: [self-hosted, spread-enabled]
    strategy:
      fail-fast: false
      matrix:
        include:
          - group: ubuntu 14.04
            task: ubuntu-14.04-64
            source: ubuntu-14.04-64
            target: ubuntu-14.04-64
          - group: ubuntu 16.04
            task: ubuntu-16.04-64
            source: ubuntu-16.04-64
            target: ubuntu-16.04-64
          - group: ubuntu 18.04
            task: ubuntu-18.04-64
            source: ubuntu-18.04-64
            target: ubuntu-18.04-64
          - group: ubuntu 20.04
            task: ubuntu-20.04-64
            source: ubuntu-20.04-64-base
            target: ubuntu-20.04-64
          - group: ubuntu 22.04
            task: ubuntu-22.04-64
            source: ubuntu-22.04-64-base
            target: ubuntu-22.04-64
          - group: ubuntu 24.04
            task: ubuntu-24.04-64
            source: ubuntu-24.04-64-base
            target: ubuntu-24.04-64
          - group: ubuntu 24.10
            task: ubuntu-24.10-64
            source: ubuntu-24.10-64-base
            target: ubuntu-24.10-64
          - group: ubuntu 25.04
            task: ubuntu-25.04-64
            source: ubuntu-25.04-64-base
            target: ubuntu-25.04-64

          - group: debian 11
            task: debian-11
            source: debian-11-64-base
            target: debian-11-64
          - group: debian 12
            task: debian-12
            source: debian-12-64-base
            target: debian-12-64
          - group: debian sid
            task: debian-sid
            source: debian-sid-64-base
            target: debian-sid-64

          - group: amazon linux 2
            task: amazon-linux-2
            source: amazon-linux-2-64-base
            target: amazon-linux-2-64
          - group: amazon linux 2023
            task: amazon-linux-2023
            source: amazon-linux-2023-64-base
            target: amazon-linux-2023-64

          - group: centos 9
            task: centos-9
            source: centos-9-64-base
            target: centos-9-64

          - group: opensuse 15.5
            task: opensuse-15-5
            source: opensuse-15.5-64-base
            target: opensuse-15.5-64
          - group: opensuse 15.6
            task: opensuse-15-6
            source: opensuse-15.6-64-base
            target: opensuse-15.6-64
          - group: opensuse tumbleweed
            task: opensuse-tumbleweed
            source: opensuse-tumbleweed-64-base
            target: opensuse-tumbleweed-64

          - group: arch linux
            task: arch-linux
            source: arch-linux-64-base
            target: arch-linux-64

    steps:
    - name: Ensure the workspace is clean
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: master

    - name: Run test
      env:
          IMAGE_BAKER_SA: ${{ secrets.IMAGE_BAKER_SA }}
      shell: bash
      run: |
          echo "$IMAGE_BAKER_SA" > sa.json
          if ! spread "google:${{ matrix.source }}:tasks/google/update-image/${{ matrix.task }}"; then
            echo "Spread images task failed, exiting..."
            exit 1
          fi
          spread "google:${{ matrix.target }}:tasks/google/common/clean-old-images"
  
    - name: Discard spread workers
      if: always()
      run: |
        shopt -s nullglob;
        for r in .spread-reuse.*.yaml; do
          spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')";
        done

    - name: Cleanup job workspace after run tests
      if: always()
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
