name: Update OS amd64 images in ps7
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 0'

jobs:
  update-image:
    name: os-amd64-ps7 (${{ matrix.group }})
    runs-on: [self-hosted, spread-enabled]
    strategy:
      fail-fast: false
      matrix:
        include:
          - group: ubuntu 16.04
            task: ubuntu-16.04-64
            source: ubuntu-16.04-64-base
            target: ubuntu-16.04-64
            property:
          - group: ubuntu 18.04
            task: ubuntu-18.04-64
            source: ubuntu-18.04-64-base
            target: ubuntu-18.04-64
            property:
          - group: ubuntu 20.04
            task: ubuntu-20.04-64
            source: ubuntu-20.04-64-base
            target: ubuntu-20.04-64
            property:
          - group: ubuntu 22.04
            task: ubuntu-22.04-64
            source: ubuntu-22.04-64-base
            target: ubuntu-22.04-64
            property:
          - group: ubuntu 24.04
            task: ubuntu-24.04-64
            source: ubuntu-24.04-64-base
            target: ubuntu-24.04-64
            property:
          - group: ubuntu 25.04
            task: ubuntu-25.04-64
            source: ubuntu-25.04-64-base
            target: ubuntu-25.04-64
            property:
          - group: ubuntu 25.10
            task: ubuntu-25.10-64
            source: ubuntu-25.10-64-base
            target: ubuntu-25.10-64
            property:

          - group: ubuntu 20.04 uefi
            task: ubuntu-20.04-64
            source: ubuntu-20.04-64-base
            target: ubuntu-20.04-64-uefi
            property: hw_firmware_type=uefi
          - group: ubuntu 22.04 uefi
            task: ubuntu-22.04-64
            source: ubuntu-22.04-64-base
            target: ubuntu-22.04-64-uefi
            property: hw_firmware_type=uefi
          - group: ubuntu 24.04 uefi
            task: ubuntu-24.04-64
            source: ubuntu-24.04-64-base
            target: ubuntu-24.04-64-uefi
            property: hw_firmware_type=uefi

          - group: debian 12
            task: debian-12-64
            source: debian-12-64-base
            target: debian-12-64
            property:

          - group: amazon-linux 2
            task: amazon-linux-2-64
            source: amazon-linux-2-base
            target: amazon-linux-2
            property: os_secure_boot=required
          - group: amazon-linux 2023
            task: amazon-linux-2023-64
            source: amazon-linux-2023-base
            target: amazon-linux-2023
            property: os_secure_boot=required

          - group: arch-linux
            task: arch-linux-64
            source: arch-linux-base
            target: arch-linux
            property:

    steps:
    - name: Ensure the workspace is clean
      run: |
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"

    - name: Checkout code
      uses: actions/checkout@v4
      with:
          ref: master

    - name: Run test
      env:
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL_AMD64_PS7 }}
          OS_IDENTITY_API_VERSION: ${{ vars.OS_IDENTITY_API_VERSION }}
          OS_INTERFACE: ${{ vars.OS_INTERFACE }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD_AMD64_PS7 }}
          OS_PROJECT_DOMAIN_NAME: ${{ vars.OS_PROJECT_DOMAIN_NAME }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME_AMD64_PS7 }}
          OS_REGION_NAME: ${{ secrets.OS_REGION_NAME_AMD64_PS7 }}
          OS_USER_DOMAIN_NAME: ${{ vars.OS_USER_DOMAIN_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME_AMD64_PS7 }}
      shell: bash
      run: |
          property_param=""
          if [ -n "${{ matrix.property }}" ]; then
            property_param="--property ${{ matrix.property }}"
          fi
          ./lib/openstack.sh update-image --no-checks --backend openstack-ps7 --task "${{ matrix.task }}" --source-system "${{ matrix.source }}" --target-system "${{ matrix.target }}" --target-image snapd-spread/"${{ matrix.target }}" $property_param
  
    - name: Discard spread workers
      if: always()
      run: |
        shopt -s nullglob;
        for r in .spread-reuse.*.yaml; do
          spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')";
        done
